export enum ETemplates {
  GUEST_REPORT_CREATED = 'GUEST REPORT CREATED',
  NEW_REQUEST_MESSAGE = 'NEW REQUEST MESSAGE',
  REQUEST_CREATED = 'REQUEST CREATED',
  UNIT_AUTH_REQUEST_APPROVED = 'UNIT AUTH REQUEST APPROVED',
  UNIT_AUTH_REQUEST_CREATED = 'UNIT AUTH REQUEST CREATED',
}
